feat: add vm networking at schedule
polyxia-org/rik pull request #15
Opened 2023-02-22 07:59 UTC by kalil-pelissier

close polyxia-org/project#21

2023-02-25 10:51 UTC, kalil-pelissier commented
This PR is ready for a first review it has to be rebased on the main (will be done by the weekend).

This is the first job to integrate networking for the function feature.
The next step is to clean a little bit the Riklet by creating a Network manager like (to create iptables rules and network interfaces)

2023-02-25 11:32 UTC, AlexandreBrg requested changes
Nice work! Some changes related to mistakes in rebase, but if it's working properly with other components, we can go forward with it!

If you need some help, don't hesitate, I'd be happy to do some pair prog with you 😉

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +        for ip in network.iter().step_by(4) {
Could you explain why this `.iter().step_by(4)` is necessary ?

A little bit of code documentation here would be useful

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +            let subnet = Ipv4Network::new(ip, 30).unwrap();
Could you add some error handling in here ?

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +>>>>>>> 141e041 (feat(riklet): read function port exposure from workload definition)
Rebase seemed to have fail here

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +>>>>>>> 141e041 (feat(riklet): read function port exposure from workload definition)
Rebase seemed to have fail here

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +pub struct IpAllocator {
Not sure to understand what this `IpAllocator` does, but here is my understand:

`IpAllocator` is used as a Singleton instance to manage IPv4 networks. When called `IpAllocator::new()`, you save in memory only 4 networks to anticipate new requests of available networks. That means, when a new instance is requested, you reserve a network and when the instance is freed, you also free the network.

Is it a right understanding ?

Some additional documentation would be awesome to have in this file!

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/core.rs
> +// const TAP_SCRIPT_DEFAULT_LOCATION: &str = "/app/setup-host-tap.sh";
Remove unused code

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/core.rs
> +const DEFAULT_AGENT_PORT: u16 = 8080;
`const` variables would be a better fit in `main.rs`

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/core.rs
> +                    )),
Didn't know about this way of format :o

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/core.rs
> +                        "console=ttyS0 reboot=k nomodules random.trust_cpu=on panic=1 pci=off tsc=reliable i8042.nokbd i8042.noaux ipv6.disable=1 quiet loglevel=0 ip={firecracker_ip}::{tap_ip}:{MASK_
Would make sense to have the static part of `boot_args` as a constant

2023-02-25 11:32 UTC, AlexandreBrg commented on riklet/src/structs.rs
> +const DEFAULT_FUNCTION_RUNTIME_PORT: u16 = 3000;
Please move constants to main.rs (or create a file `constants.rs` with all const in it)

2023-02-26 22:54 UTC, kalil-pelissier commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +pub struct IpAllocator {
It's almost that.
The IpAllocator works as a Singleton but allocates all subnet of 4 IP in the network that is passed in the `new` method.
Why 4 IP? a subnet of 4 IP means that the first IP identifies the network and the last is used for the broadcast. That leaves 2 IPs available (one for the tap IP and the other for the firecracker micro VM).

(e.g)
```bash
$ ipcalc 172.16.0.0/30  
Network:	172.16.0.0/30
Netmask:	255.255.255.252 = 30
Broadcast:	172.16.0.3

Address space:	Private Use
HostMin:	172.16.0.1
HostMax:	172.16.0.2
Hosts/Net:	2
```

2023-02-26 23:14 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +pub struct IpAllocator {
Indeed, it makes sense! That's why documentation for this in the code would be very useful to understand this 😉

2023-02-27 17:59 UTC, mflagey commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +pub struct IpAllocator {
I agree with Alexandre for more documentation of this part

2023-02-27 17:59 UTC, mflagey commented on riklet/src/cli/function_config.rs
> +    pub rootfs_location: String,
rootfs location is not used, rootfs is now downloaded from url stored in the workload

2023-02-27 17:59 UTC, mflagey commented on riklet/src/core.rs
> +        let network = Ipv4Network::new(Ipv4Addr::new(192, 168, 1, 0), 24).unwrap();
Network is hardcoded ?

2023-02-27 17:59 UTC, mflagey commented on riklet/src/core.rs
> +                    guest_mac: Some("AA:FC:00:00:00:01".to_string()),
MAC hardcoded

2023-02-28 18:24 UTC, mflagey commented
Please rebase your branch, there are conflicts :(

2023-02-28 22:35 UTC, kalil-pelissier commented
@mflagey , @AlexandreBrg  ready for the last review!

2023-03-01 16:59 UTC, AlexandreBrg requested changes
Nice work, some details to work on, but still awesome to see it works!

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +You can set this configuration as environement variable.
A table seems to be more appropriate here

```suggestion

Here is a list of **required** environment variables to run riklet:

| Environment Variable | Description | Default |
|---|---|---|
| `IFACE` | Network interface connected to the internet | "" |
| `IFACE_IP` | IP of the Network interface connected to the internet | "" |
| `FIRECRACKER_LOCATION` | Path to the firecracker binary | "" |
| `KERNEL_LOCATION` | Path to the kernel location | "" |
| `SCRIPT_LOCATION` | Path to the
[script](https://github.com/polyxia-org/rik/blob/main/scripts/setup-host-tap.sh)
that create tap interface. | "" |
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +sudo riklet --firecracker-path <FIRECRACKER_LOCATION> --kernel-path <KERNEL_LOCATION> --ifnet <IFACE> --ifnet-ip <IFACE_IP> --script-path <SCRIPT_LOCATION>
Please consider put the table of variable needed here, and then you can refer them with `${NAME}` in your example command. 

That way it might be clearer to determine that variables are needed at first, then user is able to run

```suggestion
sudo riklet --firecracker-path ${FIRECRACKER_LOCATION} \
    --kernel-path ${KERNEL_LOCATION} --ifnet ${IFACE} \
    --ifnet-ip ${IFACE_IP} --script-path ${SCRIPT_LOCATION}
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +For now the Riklet don't clean his network configuration by his self.
```suggestion
For now the Riklet doesn't clean its network configuration by itself.
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +sudo iptables -D FORWARD -i rik-<FUNCTION_NAME>-tap -o <IFACE> -j ACCEPT
```suggestion
sudo iptables -D FORWARD -i rik-${FUNCTION_NAME}-tap -o ${IFACE} -j ACCEPT
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +sudo iptables -t nat -D POSTROUTING -o <IFACE> -j MASQUERADE
```suggestion
sudo iptables -t nat -D POSTROUTING -o ${IFACE} -j MASQUERADE
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/README.md
> +`FUNCTION_NAME`: the name of the function that is scheduled.
Please move this to a table above the shell example

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +    network: Ipv4Network,
`network` property looks like dead code, would you mind delete this ?

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/crates/shared/src/utils/ip_allocator.rs
> +            .filter(|subnet| *subnet.1 == true)
Evaluation of boolean is not necessary here

```suggestion
            .filter(|subnet| *subnet.1)
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +        help = ""
A local configuration file would be preferred, as we don't want to "pollute" file systems.
 
```suggestion
        short,
        long,
        default_value = "riklet.toml"
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +        default_value = "/app/fireckracker"
```suggestion
        default_value = "/app/firecracker"
```

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +    pub firecracker_path: String,
Generally, `PathBuf` is preferred as they are more convient to work with. Also, it will prevent trash values in this field

2023-03-01 16:59 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +    )]
Default values should define the most frequent situation `/app/file` would match a very specific situation, which is a container build / prepared images. I guess the most frequent situation is having those file where the user run the program (`default_value="vmlinux.bin"`)

2023-03-01 21:21 UTC, kalil-pelissier commented on riklet/src/cli/mod.rs
> +        help = ""
I don't want to mess with this configuration (I'm not the author). I think that the default configuration is set to this path to it has to stay like this for the moment.

2023-03-01 21:44 UTC, AlexandreBrg commented on riklet/src/cli/mod.rs
> +        help = ""
ok

2023-03-01 21:45 UTC, AlexandreBrg approved these changes

2023-03-01 22:09 UTC, MaloPolese approved these changes
![image](https://user-images.githubusercontent.com/37849933/222276307-6feb64c7-9081-48f1-b696-8026e7edb8f4.png)

2023-03-01 22:10 UTC, MaloPolese commented
you did it, congratulations 🥳

2023-03-02 09:14 UTC, merged