[feat] make core components more clearer
polyxia-org/rik pull request #9
Opened 2023-02-16 23:59 UTC by AlexandreBrg

2023-02-18 12:25 UTC, AlexandreBrg commented on controller/src/core/core.rs
> +use proto::common::worker_status::Status;
Done

2023-02-19 18:20 UTC, hugoamalric requested changes
Could you please also resolve all warnings if possible ?

2023-02-19 18:20 UTC, hugoamalric commented on controller/src/core/instance_service.rs
> +            Err(_e) => "http://127.0.0.1:4996".to_string(),
Hard coded localhost ip ?
Better to put it in a variable

2023-02-19 23:33 UTC, AlexandreBrg commented on controller/src/core/instance_service.rs
> +            Err(_e) => "http://127.0.0.1:4996".to_string(),
Done

2023-02-19 23:35 UTC, AlexandreBrg commented
> Could you please also resolve all warnings if possible ?

I removed all warnings, except warnings related to dead code.

2023-02-20 07:53 UTC, hugoamalric approved these changes

2023-02-20 08:12 UTC, MaloPolese approved these changes

2023-02-20 08:14 UTC, merged